[package]
name = "rustLector"
version = "0.1.0"
edition = "2024"

[dependencies]
serialport = "4.2.2"   # Para la comunicación serial
serde = { version = "1.0", features = ["derive"] } # Para deserializar (parsear)
serde_json = "1.0"     # Específicamente para JSON